### ISSUE TITLE
Position of the widget is not inside the taskbar

### ISSUE THREAD

**Issue by humantorch10** [Khiro95/Awqat-Salaat#13]
Hi, I found an issue in the position of the widget in the taskbar, here is how it looks:
![image](https://github.com/Khiro95/Awqat-Salaat/assets/65015755/d553df32-d179-48bd-995d-2f17030a0809)

I think a possible cause for this issue is that, I have a 2 in 1 laptop that could work as tablet, so the taskbar size and look changes to appear bigger and the look and position of the widget is correct in this mode.
![image](https://github.com/Khiro95/Awqat-Salaat/assets/65015755/db85dd2e-011c-48e6-8d22-bc223b9d974a)

I know, I might be in the minority here, but I would be glad if you could find a solution for it.

**Comment by Khiro95** [comment]
Hello and thank you for reporting the issue!

I have few questions to understand the situation:
- Does the issue occur when you launch the widget or when you change tablet mode while the widget is already running?
- What happen if you right-click on the widget and click on **Re-position** (**إعادة التموقع**)? Does it fix the issue?
- Does the issue get fixed if you hide the widget then show it again? Or you have to close it completely then relaunch it?

**Comment by humantorch10** [comment]
Hi, thank you for responding.

- Yes, the issue happen when I launch the widget. The thought of switching to tablet mode occurred to me when I noticed that the widget was slightly elevated above the taskbar. I’m aware that the taskbar height increases in tablet mode, and that’s when I discovered that the widget’s position gets corrected in this mode.
- No, it doesn’t have any effect.
- No, neither hiding the widget nor relaunching it resolves the issue.

**Comment by Khiro95** [comment]
@humantorch10 Thank you for the useful feedback.

Looks like your case is a little special, but no worries I will try to fix the problem.

However, I still have some questions and this time they are about your first screenshot. It shows an unexpected size of the widget:
- Did you disable countdown in widget Settings?
- What happen if you enable/disable **Show countdown** (**إظهار العد التنازلي**)?

Also, I would like yo know if your display scale is 100% or higher.

Thanks again.

**Comment by humantorch10** [comment]
Hello @Khiro95,

In Response to your questions, yes, however, another issue has surfaced. The option to enable/disable the countdown doesn’t seem to have any impact. It doesn’t display anything, and disabling it doesn’t alter the widget’s size. As for the display scale, it’s set to 200%, and my display resolution is 2.8k.

I hope my answer fulfills your questions.

Thank you for taking the time to look at this issue.

**Comment by Khiro95** [comment]
@humantorch10 Hello, and thanks again for the infos.

Actually there is a problem with the width of the widget since it doesn't respect DPI scale, thus the content is clipped. However, this problem is fixed in the next version.

I will try to fix tablet mode issue in the next version as well :)

**Comment by humantorch10** [comment]
Thanks a lot for your consideration.

**Comment by Khiro95** [comment]
@humantorch10 You are welcome :)

I wonder if you are willing to help me test a potential fix for this problem.

Unfortunately, I'm unable to test your case since I don't have a 2-in-1 device which support tablet mode, and I couldn't make Windows 11 switch to that mode in VM. A touchscreen is required :(
So the best I can do is to guess, thus I need other people to test the fix.

I'm planning to ship that *untested* fix in the next release (coming soon), but if it doesn't work then the real fix will come late.

**Comment by humantorch10** [comment]
Hi, @Khiro95 

Of course, I will gladly want to test it, just tell me what I need to do to test it.

**Comment by Khiro95** [comment]
Hi @humantorch10 and thanks a lot!

Actually, I managed to make the taskbar behave similarly to yours when tablet mode is disabled, so I finally can reproduce your problem:
![image](https://github.com/Khiro95/Awqat-Salaat/assets/126525910/6714ed3c-6587-407d-8e28-e5f3bcafe355)

That's a good news because I can now fix it. However, since I cannot switch to tablet mode, I still need help with testing the dynamic switch while the widget is running.

So here is a zip containing a testing version (no installation is required) that should fix 2 issues:
- The vertical position of the widget.
- The width of the widget when display scale is not 100%.

Launch it and see if these two issues are fixed for you. Also switch to/from tablet mode while it's running and let me know if it react to that change and adapt automatically.

[AwqatSalaat.WinUI.Issue_13.zip](https://github.com/Khiro95/Awqat-Salaat/files/15321866/AwqatSalaat.WinUI.Issue_13.zip)

Thank you for your help :)

**Comment by humantorch10** [comment]
Hi @Khiro95,

Firstly, I’d like to express my sincere appreciation for the time and effort you’ve dedicated to enhancing this fantastic application.

’m pleased to inform you that both the vertical alignment and the width of the widget have been successfully adjusted 😊. However, there are still some issues with the widget’s automatic adaptation when transitioning between tablet and normal modes, which I will demonstrate with the following images:

The first image depicts the initial state upon launching the app, where everything appears to be good.
![Screenshot 2024-05-15 194508](https://github.com/Khiro95/Awqat-Salaat/assets/65015755/e3c5f53b-af0f-4f0d-806f-a989c97b1b82)

Upon switching to tablet mode, as shown in the second image, the widget seems to be vertically off-center compared to the image in my original post. However, I’ll leave the final judgment to you.
![Screenshot 2024-05-15 200239](https://github.com/Khiro95/Awqat-Salaat/assets/65015755/5cf9c7fe-6bf7-44f8-97d7-6f53c8173db0)

The third image shows the appearance when reverting back to normal mode. It mirrors the initial state, which is a positive outcome.
![Screenshot 2024-05-15 200404](https://github.com/Khiro95/Awqat-Salaat/assets/65015755/1a475547-cdba-4922-aa1b-d9c203f87816)

That covers the first scenario. The second scenario involves clicking on ‘reposition’ in tablet mode and observing the results.

The fourth image displays the appearance in tablet mode after clicking ‘reposition’ from the initial state. In my view, it still appears vertically off-center, but I’m interested in hearing your thoughts as well.
![Screenshot 2024-05-15 200645](https://github.com/Khiro95/Awqat-Salaat/assets/65015755/80ffd4e6-669f-4156-bcfd-1a196eb6c078)

Upon returning to normal mode, as shown in the fifth image, the original issue reappears, with the widget possibly positioned even higher above the taskbar than before.
![Screenshot 2024-05-15 201412](https://github.com/Khiro95/Awqat-Salaat/assets/65015755/ea4df015-df05-4d08-be3d-737e7d5949a9)

Finally, after clicking the ‘reposition’ button, the issue is resolved and the widget returns to its initial appearance, as shown in the last image.
![Screenshot 2024-05-15 194508](https://github.com/Khiro95/Awqat-Salaat/assets/65015755/203bf109-badf-499e-87da-4bbacd28d70a)

Before concluding, I want to extend my heartfelt thanks for your dedication to resolving even the smallest of issues. Personally, I am content with the current state of the widget, and while the automatic adaptation feature isn’t essential for me as long as the ‘reposition’ function operates as intended, it would certainly be a wonderful addition if you could implement it.

I hope my demonstration has been helpful and clear. 

Thank you once again for your hard work.

**Comment by Khiro95** [comment]
Hi @humantorch10 and thank you for your kind words. Seeing the users of this widget happy encourages me to work harder to polish it and make it close to perfect. And at the end, I'm seeking reward from Allah and insha'Allah everyone who contributed, by giving suggestions or reporting issues or any kind of help, will have a share of this reward.

I really appreciate your high attitude and your time spent on helping me with the tests.

Your wonderful feedback and detailed report helped me a lot and I think I found the issue with the automatic adaptation. So here is an other zip file for another testing version that should finally have the correct fixes.
[AwqatSalaat.WinUI.Issue_13_2.zip](https://github.com/Khiro95/Awqat-Salaat/files/15326347/AwqatSalaat.WinUI.Issue_13_2.zip)

And I apologize if I'm asking much, but please bear with me, at the moment you're my only hope for having this problem fixed at early stage insha'Allah.

Also since you are somewhat a "touchscreen user", I would like to hear your opinion about accessibility of the widget using touch instead of mouse & keyboard:
- Do you find the widget touch-friendly? If not, which areas need improvements?
- When tablet mode is enabled, do you think the widget should grow vertically or keep the original height?

Thanks again for the help :)

**Comment by humantorch10** [comment]
Hi @Khiro95, thank you for your continuous support and dedication to improving this widget app. Your passion and commitment are truly inspiring. And I hope it will be an ongoing reward for you from Allah. 

I've downloaded and tested the current version, and unfortunately, the widget doesn't automatically adjust when I switch to tablet mode. However, the reposition button is now functional in tablet mode, allowing the widget to center vertically. Also, when reverting to normal mode, it doesn't adjust automatically, and I need to use the reposition button to center it. The key point is that the reposition button is now operating as expected.

I had hoped for the auto-adjust feature to work, but it still fails to detect the switch to and from tablet mode.

As for the tablet mode and the widget's appearance, I find its size in tablet mode to be satisfactory, and a vertical grow could also be visually appealing, so I remain neutral on this aspect. The widget's performance and appearance in touch screen mode are satisfactory, and I can't think of any improvements at this time.

Thank you very much for your efforts, and I am eager to assist and test any future updates or fixes.

**Comment by Khiro95** [comment]
Hi @humantorch10, thanks a lot for your collaboration.

Unfortunately, I will need to make advanced diagnostics with appropriate tools to fix the issue of automatic adaptation to/from tablet mode. With that being said, I'm glad that we have narrowed down the problem to a smaller issue. I will now start finishing the update to v3.1 so it should be available in the next few days insha'Allah. However, I will keep looking for a solution to the remaining issue and I hope to make it solved in future versions.

Once again, thank you for your help.

**Comment by Khiro95** [comment]
Insha'Allah after releasing v3.1 update, I will try to start working on v3.2 by first fixing the issue of automatic adaptation to/from tablet mode. I already have at least 2 other potential fixes in my head, but I don't want to let people wait more for v3.1 which contain important bugfixes and improvement. So we will continue with new tests after few days and insh'Allah we will find a solution to close this issue forever (or until Microsoft break something).

**Comment by humantorch10** [comment]
Hi @Khiro95, I just want to share this link with you, if it could help you in testing the taskbar look in touch mode.
https://itstechbased.com/how-to-enable-the-tablet-optimized-taskbar-in-windows-11-on-any-pc/

**Comment by humantorch10** [comment]
@Khiro95, I am very pleased to have been of help to you. ❤️

**Comment by Khiro95** [comment]
Hi @humantorch10 I've just released v3.1 now, please update and let me know if the problem is solved or not.

**Comment by sfksuperman** [comment]
@Khiro95 Again some issue with overlapping

![image](https://github.com/Khiro95/Awqat-Salaat/assets/34414624/cd686024-7d88-479a-a196-04fb05b5e838)

**Comment by Khiro95** [comment]
> @Khiro95 Again some issue with overlapping. It comes and goes like this.
> 
> ![image](https://private-user-images.githubusercontent.com/34414624/332007848-cd686024-7d88-479a-a196-04fb05b5e838.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMTE2MzIsIm5iZiI6MTcxNjIxMTMzMiwicGF0aCI6Ii8zNDQxNDYyNC8zMzIwMDc4NDgtY2Q2ODYwMjQtN2Q4OC00NzlhLWExOTYtMDRmYjA1YjVlODM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEzMjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZjI1MjY3YzUyZGE3ZGY5NGQxOWZjMTY5ZTg2N2E0N2Y0YTFlYTBjZWU1MzUwOTExNzQ5YjE3ZGQyNjM0NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sUgArVEJHbLETq8Q1tJTFJj7lZlrF4OFUbN8PaBvG90)

1. Are you sure the problem is caused by **Awqat Salaat WinUI** widget and not caused by **Traffic Monitor** widget?
2. If possible, please continue discussion in your other issue or open a new one, so that we keep this one for tablet mode issues 😅

**Comment by humantorch10** [comment]
I am pleased to inform you that my issue has been resolved with version 3.2.

I experimented with 3.1 for a while and encountered numerous problems, including the dynamic update of positioning not working, so I decided to wait for the next release. With version 3.2, everything is functioning properly.

I am sharing this with you so that you can finally close the issue.

**Comment by Khiro95** [comment]
@humantorch10 I'm very happy to hear that this issue is resolved!

Thank you too for helping to improve the widget in tablet mode. May Allah reward you.
